name = "furi_analytics"

[server]
  port = 3003
  host = "0.0.0.0"
  cors_addr = "https://www.furi.live:8443"

[timescale]
  host = "timescaledb"
  port = 5432
  user = "user"
  password = "pass"
  db = "analytics"
