name = "furi"
uri_size = 7
domain = "https://furi.live"

[server]
  port = 3000
  host = "0.0.0.0"
  cors_addr = "https://www.furi.live:8443"

[redis]
  host = "redis"

[postgres]
  host = "postgres"
  port = 5432
  user = "user"
  password = "password"
  db = "db"

[timescale]
  host = "timescaledb"
  port = 5432
  user = "user"
  password = "password"
  db = "analytics"
  buffer_size = 100
  flush_interval = 10

[geoip]
  country_file = "geoip/GeoLite2-Country.mmdb"
  city_file = "geoip/GeoLite2-City.mmdb"
